### ISSUE TITLE
Comment syntax breaks copy and paste

### ISSUE THREAD

**Issue by cogmind** [DigNeurosurgeon/TREMOR12P#2]
`%matplotlib inline`

Row 4. This looks like a MATLAB style comment and will break in Python, if users copy and paste from Jupyter code blocks.

**Comment by DigNeurosurgeon** [comment]
This is valid IPython code AFAIK

**Comment by cogmind** [comment]
Yes, sorry I just learned (https://ipython.org/ipython-doc/3/interactive/tutorial.html). I am working on a non-interactive implementation, which should read files from command line arguments. I am just getting started with jupyter.
